# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ranking/v1/ranking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ranking/v1/ranking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ranking/v1/ranking.proto\x12\x0fgift.ranking.v1\"\xa7\x01\n\x0cQueryContext\x12\x10\n\x08occasion\x18\x01 \x01(\t\x12\x14\n\x0crelationship\x18\x02 \x01(\t\x12\x11\n\tinterests\x18\x03 \x03(\t\x12\x14\n\x0c\x62udget_cents\x18\x04 \x01(\x03\x12\x1a\n\rrecipient_age\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x10recipient_gender\x18\x06 \x01(\tB\x10\n\x0e_recipient_age\"\xe0\x01\n\tCandidate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x0b\x63\x61tegory_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\rcategory_name\x18\x03 \x01(\t\x12\x13\n\x0bprice_cents\x18\x04 \x01(\x03\x12\x1c\n\x0f\x61ge_restriction\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\r\n\x05title\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x1b\n\x13\x61lready_in_wishlist\x18\x08 \x01(\x08\x42\x0e\n\x0c_category_idB\x12\n\x10_age_restriction\"\xa1\x01\n\x0bRankRequest\x12\x14\n\x0cselection_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05top_n\x18\x03 \x01(\x05\x12,\n\x05query\x18\x04 \x01(\x0b\x32\x1d.gift.ranking.v1.QueryContext\x12.\n\ncandidates\x18\x05 \x03(\x0b\x32\x1a.gift.ranking.v1.Candidate\")\n\x0b\x45xplanation\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x88\x01\n\nRankedItem\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x32\n\x0c\x65xplanations\x18\x03 \x03(\x0b\x32\x1c.gift.ranking.v1.Explanation\x12!\n\x19\x61lternative_candidate_ids\x18\x04 \x03(\t\"Q\n\x0cRankResponse\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.gift.ranking.v1.RankedItem\x12\x15\n\rmodel_version\x18\x02 \x01(\t2U\n\x0eRankingService\x12\x43\n\x04Rank\x12\x1c.gift.ranking.v1.RankRequest\x1a\x1d.gift.ranking.v1.RankResponseBeZcgithub.com/ilyaytrewq/Gift_Suggestion_Web_Service/internal/platform/mlgrpc/gen/ranking/v1;rankingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ranking.v1.ranking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zcgithub.com/ilyaytrewq/Gift_Suggestion_Web_Service/internal/platform/mlgrpc/gen/ranking/v1;rankingv1'
  _globals['_QUERYCONTEXT']._serialized_start=46
  _globals['_QUERYCONTEXT']._serialized_end=213
  _globals['_CANDIDATE']._serialized_start=216
  _globals['_CANDIDATE']._serialized_end=440
  _globals['_RANKREQUEST']._serialized_start=443
  _globals['_RANKREQUEST']._serialized_end=604
  _globals['_EXPLANATION']._serialized_start=606
  _globals['_EXPLANATION']._serialized_end=647
  _globals['_RANKEDITEM']._serialized_start=650
  _globals['_RANKEDITEM']._serialized_end=786
  _globals['_RANKRESPONSE']._serialized_start=788
  _globals['_RANKRESPONSE']._serialized_end=869
  _globals['_RANKINGSERVICE']._serialized_start=871
  _globals['_RANKINGSERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
